name: contains_value_and_time
description: This function for find value in List datas
version: 1.0.0
repository: https://github.com/Namoz007/containsValueAndTime-package.git
homepage: https://github.com/Namoz007/containsValueAndTime-package.git
authors:
  - Muhammadzohid Qahramonov

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

